### ISSUE TITLE
VT5, VT10, VT11 -  Maps

### ISSUE THREAD

**Issue by gswain2** [mapping-elections/site#86]
We have not been consistent with the maps (and pop-ups) with district-only vs. county-level data. 

**VT 5th (1796)**
[District 1](https://elections.lib.tufts.edu/catalog/mc87pr32f): Correct (based on the third ballot)
[District 2](https://elections.lib.tufts.edu/catalog/x920fx334): NNV only has district totals and lists 3 of 6 counties. Our map leaves all counties in District 2 blank. To fix: Fill in Orange, Windham, and Winsor counties based on district party percentages (99.3% Federalist), add pop-up for these three counties which gives district party percentages and the "County-level returns are not available" message

**VT 10th (1806)**
[District 1/Southwest](https://elections.lib.tufts.edu/catalog/nv9354169): NNV has district-level vote totals. Our map is blank. To fix: fill in both counties based on district party percentages, add pop-up for these  counties which gives district party percentages and the "County-level returns are not available" message
[District 2/Southeast](https://elections.lib.tufts.edu/catalog/9880vs43j): NNV has district-level vote totals. Our map is blank. To fix: fill in both counties based on district party percentages, add pop-up for these  counties which gives district party percentages and the "County-level returns are not available" message
[District 3/Northeast](https://elections.lib.tufts.edu/catalog/6969z220d): Correct 
[District 4/Northwest](https://elections.lib.tufts.edu/catalog/g158bj669): Correct 

**VT 11th (1808)**
[District 1/Southwest](https://elections.lib.tufts.edu/catalog/cr56n134j): NNV has district-level vote totals. Our map is blank. To fix: fill in counties based on district party percentages, add pop-up for these counties which gives district party percentages and the "County-level returns are not available" message
[District 2/Southeast](https://elections.lib.tufts.edu/catalog/jq085k951): Correct (based on 2nd ballot)
[District 3/Northeast](https://elections.lib.tufts.edu/catalog/8w32r6893): Correct (based on 2nd ballot)
[District 4/Northwest](https://elections.lib.tufts.edu/catalog/5x21tg84f): NNV has district-level vote totals. Our map is blank. To fix: fill in counties based on district party percentages, add pop-up for these counties which gives district party percentages and the "County-level returns are not available" message

**Comment by lmullen** [comment]
@gswain2 Okay, with the NNV links I remember our line of reasoning here. We have been filling in county percentages from districts when the district information is available and the county is not. But we are very cautious about not contradicting information that is available in NNV, because we are already right on the edge of the fallacy of division. In these instances it is not that there is no data available. It's that the data is available at the level of the town not the county, but the sums of the town votes in many instances do not add up to the district totals, meaning that there were votes in the counties not included in the town votes. We can't generalize both up and down geographically at the same time, so we elected to leave these blank. I think we've already done the best we can safely do here.
